<a href="https://colab.research.google.com/github/hvmt2003/Logistic-Regression/blob/main/Imbalanced_Data_Handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
dataset=pd.read_excel('/content/Social_Network_Ads.xlsx')

In [3]:
dataset

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [5]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
x=dataset.iloc[:,:-1]
y=dataset['Purchased']

In [10]:
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [11]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
lr=LogisticRegression()

In [16]:
lr.fit(x_train,y_train)

LogisticRegression()

In [18]:
lr.score(x_test,y_test)

0.8875

In [19]:
lr.predict([[19,19000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

### **Data is biased**

In [20]:
lr.predict([[45,2600]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [21]:
lr.predict([[46,28000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

### **Dataset Balancing Random Under Sampling**

In [22]:
from imblearn.under_sampling import RandomUnderSampler

In [25]:
ru=RandomUnderSampler()
ru_x,ru_y=ru.fit_resample(x,y)

In [26]:
ru_x

     Age  EstimatedSalary
129   26            84000
189   28            32000
104   19            21000
44    28            84000
32    21            16000
..   ...              ...
393   60            42000
395   46            41000
396   51            23000
397   50            20000
399   49            36000

[286 rows x 2 columns]

In [27]:
ru_y

129    0
189    0
104    0
44     0
32     0
      ..
393    1
395    1
396    1
397    1
399    1
Name: Purchased, Length: 286, dtype: int64

In [28]:
ru_y.value_counts()

Purchased
0    143
1    143
Name: count, dtype: int64

In [29]:
x_train1,x_test1,y_train1,y_test1=train_test_split(ru_x,ru_y,test_size=0.2,random_state=42)

In [30]:
lr1=LogisticRegression()
lr1.fit(x_train1,y_train1)

LogisticRegression()

In [31]:
lr1.score(x_test1,y_test1)

0.8275862068965517

In [35]:
lr.predict([[45,26000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [37]:
from imblearn.over_sampling import RandomOverSampler

In [38]:
ro=RandomOverSampler()
ro_x,ro_y=ro.fit_resample(x,y)

In [39]:
ro_x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
509   49            89000
510   35           147000
511   39           106000
512   47            20000
513   55           125000

[514 rows x 2 columns]

In [40]:
ro_y.value_counts()

Purchased
0    257
1    257
Name: count, dtype: int64

In [41]:
x_train2,x_test2,y_train2,y_test2=train_test_split(ro_x,ro_y,test_size=0.2,random_state=42)

In [42]:
lr2=LogisticRegression()
lr2.fit(x_train2,y_train2)

LogisticRegression()

In [43]:
lr2.score(x_test2,y_test2)

0.8446601941747572

In [44]:
lr1.predict([[45,26000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])